# -*- coding: utf-8 -*-
"""portofolio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17i-uihHi00exzIBJR87kJQfWCnErXoSU
"""

#BISMILLAHIRROHMANIRROHIM

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

bit = pd.read_csv('/content/Health_AnimalBites.csv')
bit.head()

#menghapus kolom tak perlu
bit = bit.drop(columns=['vaccination_yrs','victim_zip','AdvIssuedYNDesc','quarantine_date',
                        'DispositionIDDesc','head_sent_date','release_date'])
bit.head()

#to date time
bit['bite_date'] = bit['bite_date'].replace(['5013-07-15 00:00:00'],'2013-07-15 00:00:00')
bit['bite_date'] = pd.to_datetime(bit['bite_date'])
bit['vaccination_date'] = pd.to_datetime(bit['vaccination_date'])

#cleaning data nan
bit['SpeciesIDDesc'] = bit['SpeciesIDDesc'].fillna('OTHER')
bit['BreedIDDesc'] = bit['BreedIDDesc'].fillna('UNKNOWN')
bit['GenderIDDesc'] = bit['GenderIDDesc'].fillna('UNKNOWN')
bit['color'] = bit['color'].fillna('UNKNOWN')
bit['WhereBittenIDDesc'] = bit['WhereBittenIDDesc'].fillna('UNKNOWN')
bit['ResultsIDDesc'] = bit['ResultsIDDesc'].fillna('UNKNOWN')

#mengubah ke huruf kecil
bit['SpeciesIDDesc'] = bit['SpeciesIDDesc'].str.lower()
bit['BreedIDDesc'] = bit['BreedIDDesc'].str.lower()
bit['GenderIDDesc'] = bit['GenderIDDesc'].str.lower()
bit['color'] = bit['color'].str.lower()
bit['WhereBittenIDDesc'] = bit['WhereBittenIDDesc'].str.lower()
bit['ResultsIDDesc'] = bit['ResultsIDDesc'].str.lower()

#menghapus seluruh duplikasi baris
bit.drop_duplicates(inplace=True)
bit

bit.info()

#jumlah banyak kasus gigitan hewan
x = bit['SpeciesIDDesc']
plt.hist(x, bins=10, color='red', edgecolor='black')
plt.show()

sns.histplot(x='SpeciesIDDesc', data=bit)
plt.show()

sns.histplot(data=bit, x='WhereBittenIDDesc')
plt.show()

plt.hist(bit['ResultsIDDesc'], bins=10, color='green', edgecolor='black')
plt.title('Rabies or Not')
plt.xlabel('Results')
plt.ylabel('Counts')
plt.show()

rabies = bit.groupby('ResultsIDDesc')
positive = rabies.get_group('positive')
positive

animal = bit.groupby('SpeciesIDDesc')

dog = animal.get_group('dog')
dog

raccoon = animal.get_group('raccoon')
raccoon

ferret = animal.get_group('ferret')
ferret

breed_dog = bit[bit['SpeciesIDDesc']=='dog']
breed_dog

count_breed_dog = pd.DataFrame(breed_dog['BreedIDDesc'].value_counts())
count_breed_dog

cat = bit[bit['SpeciesIDDesc']=='cat']
cat

count_breed_cat = pd.DataFrame(cat['BreedIDDesc'].value_counts())
count_breed_cat